/* TABLE: chrome:// */
'use strict';

function outputChrome() {

// FF only
if (isNaN(window.mozInnerScreenX) === false) {
	dom.jsHash = "tests are running"
	dom.cssHash = "give it 5 seconds"
	let b = "chrome://branding/content/",
		c = "chrome://browser/content/",
		ca = c + "abouthome/",
		cb = c + "browser",
		cd = c + "devtools/",
		ce = c + "devltools/debugger",
		cf = c + "devtools/performance/",
		cl = c + "loop/shared/",
		cp = c + "preferences/",
		cr = c + "parent/",
		ci = c + "preferences/in-content",
		cq = c + "pocket/panels/",
		ct = c + "defaultthemes/",
		g = "chrome://global/content/",
		s = "chrome://browser/skin/",
		sc = s + "customizableui/",
		sd = s + "devtools/",
		se = s + "controlcenter/",
		sf = s + "downloads/",
		sn = s + "notification-icons/",
		sp = s + "preferences/",
		sq = s + "places/",
		st = s + "tabbrowser/",
		sy = s + "yosemite/",
		sx = s + "syncProgress"

	let jsUris = [c+'ext-android.js',c+'aboutDialog-appUpdater.js',c+'aboutDialog.js',c+'aboutNetError.js',c+'aboutPrivateBrowsing.js',
	c+'aboutRestartRequired.js',c+'aboutRobots.js',c+'aboutSessionRestore.js',c+'aboutTabCrashed.js',c+'aboutTabGroupsMigration.js',
	c+'aboutaccounts/aboutaccounts.js',c+'abouthealthreport/abouthealth.js',ca+'aboutHome.js',c+'blockedSite.js',c+'bookmarks/bookmarksPanel.js',
	c+'bookmarks/sidebarUtils.js',cb+'-addons.js',cb+'-allTabsMenu.js',cb+'-captivePortal.js',cb+'-compacttheme.js',cb+'-ctrlTab.js',
	cb+'-customization.js',cb+'-data-submission-info-bar.js',cb+'-devedition.js',cb+'-eme.js',cb+'-feeds.js',cb+'-fullScreen.js',
	cb+'-fullScreenAndPointerLock.js',cb+'-fullZoom.js',cb+'-fxaccounts.js',cb+'-gestureSupport.js',cb+'-media.js',cb+'-pageActions.js',
	cb+'-places.js',cb+'-plugins.js',cb+'-refreshblocker.js',cb+'-safebrowsing.js',cb+'-sidebar.js',cb+'-siteIdentity.js',cb+'-social.js',
	cb+'-sync.js',cb+'-syncui.js',cb+'-tabsintitlebar.js',cb+'-thumbnails.js',cb+'-trackingprotection.js',cb+'-webrender.js',cb+'.js',
	c+'child/ext-browser.js',c+'child/ext-devtools-inspectedWindow.js',c+'child/ext-devtools-network.js',c+'child/ext-devtools-panels.js',
	c+'child/ext-devtools.js',c+'child/ext-menus.js',c+'child/ext-omnibox.js',c+'child/ext-tabs.js',c+'content-UITour.js',
	c+'content-refreshblocker.js',c+'content-sessionStore.js',c+'content.js',c+'contentSearchUI.js',c+'customizableui/panelUI.js',
	cd+'animationinspector/animation-controller.js',cd+'animationinspector/animation-panel.js',cd+'app-manager/connection-footer.js',
	cd+'app-manager/device.js',cd+'app-manager/index.js',cd+'app-manager/manifest-editor.js',cd+'app-manager/projects.js',
	cd+'app-manager/template.js',cd+'app-manager/utils.js',cd+'canvasdebugger.js',cd+'canvasdebugger/callslist.js',
	cd+'canvasdebugger/snapshotslist.js',cd+'codemirror/activeline.js',cd+'codemirror/brace-fold.js',cd+'codemirror/clike.js',
	cd+'codemirror/closebrackets.js',cd+'codemirror/codemirror.js',cd+'codemirror/comment-fold.js',cd+'codemirror/comment.js',
	cd+'codemirror/css.js',cd+'codemirror/dialog.js',cd+'codemirror/emacs.js',cd+'codemirror/foldcode.js',cd+'codemirror/foldgutter.js',
	cd+'codemirror/htmlmixed.js',cd+'codemirror/javascript.js',cd+'codemirror/matchbrackets.js',cd+'codemirror/search.js',
	cd+'codemirror/searchcursor.js',cd+'codemirror/show-hint.js',cd+'codemirror/sublime.js',cd+'codemirror/tern.js',
	cd+'codemirror/trailingspace.js',cd+'codemirror/vim.js',cd+'codemirror/xml-fold.js',cd+'codemirror/xml.js',
	cd+'commandline/commands-index.js',cd+'connect.js',cd+'d3.js',cd+'dagre-d3.js',ce+'-controller.js',ce+'-panes.js',ce+'-toolbar.js',
	ce+'-view.js',ce+'/event-listeners-view.js',ce+'/filter-view.js',ce+'/global-search-view.js',ce+'/options-view.js',ce+'/sources-view.js',
	ce+'/stack-frames-classic-view.js',ce+'/stack-frames-view.js',ce+'/toolbar-view.js',ce+'/tracer-view.js',ce+'/utils.js',
	ce+'/variable-bubble-view.js',ce+'/watch-expressions-view.js',ce+'/workers-view.js',cd+'fontinspector/font-inspector.js',
	cd+'frame-script-utils.js',cd+'framework/toolbox-options.js',cd+'framework/toolbox-process-window.js',cd+'layoutview/view.js',
	cd+'memory/controller.js',cd+'netmonitor-controller.js',cd+'netmonitor-view.js',cf+'performance-controller.js',cf+'performance-view.js',
	cf+'system.js',cf+'views/details-js-call-tree.js',cf+'views/details-js-flamegraph.js',cf+'views/details-memory-call-tree.js',
	cf+'views/details-memory-flamegraph.js',cf+'views/details-optimizations.js',cf+'views/details-subview.js',cf+'views/details-waterfall.js',
	cf+'views/details.js',cf+'views/frames-list.js',cf+'views/jit-optimizations.js',cf+'views/optimizations-list.js',cf+'views/overview.js',
	cf+'views/recordings.js',cf+'views/toolbar.js',cd+'profiler.js',cd+'profiler/cleopatra/js/ProgressReporter.js',
	cd+'profiler/cleopatra/js/devtools.js',cd+'profiler/cleopatra/js/parser.js',cd+'profiler/cleopatra/js/parserWorker.js',
	cd+'profiler/cleopatra/js/strings.js',cd+'profiler/cleopatra/js/tree.js',cd+'profiler/cleopatra/js/ui.js',cd+'projecteditor-loader.js',
	cd+'promisedebugger/promise-controller.js',cd+'promisedebugger/promise-debugger.js',cd+'promisedebugger/promise-panel.js',cd+'readdir.js',
	cd+'responsivedesign/resize-commands.js',cd+'scratchpad-commands.js',cd+'scratchpad.js',cd+'shadereditor.js',cd+'theme-switching.js',
	cd+'timeline/timeline.js',cd+'ui-profile.js',cd+'ui-recordings.js',cd+'webaudioeditor-controller.js',cd+'webaudioeditor-view.js',
	cd+'webaudioeditor/controller.js',cd+'webaudioeditor/includes.js',cd+'webaudioeditor/models.js',cd+'webaudioeditor/views/automation.js',
	cd+'webaudioeditor/views/context.js',cd+'webaudioeditor/views/inspector.js',cd+'webaudioeditor/views/properties.js',
	cd+'webaudioeditor/views/utils.js',c+'downloads/allDownloadsView.js',c+'downloads/allDownloadsViewOverlay.js',
	c+'downloads/contentAreaDownloadsView.js',c+'downloads/downloads.js',c+'downloads/indicator.js',c+'ext-bookmarks.js',c+'ext-browser.js',
	c+'ext-browserAction.js',c+'ext-browsingData.js',c+'ext-c-browser.js',c+'ext-c-contextMenus.js',c+'ext-c-devtools-inspectedWindow.js',
	c+'ext-c-devtools-network.js',c+'ext-c-devtools-panels.js',c+'ext-c-devtools.js',c+'ext-c-menus.js',c+'ext-c-omnibox.js',c+'ext-c-tabs.js',
	c+'ext-chrome-settings-overrides.js',c+'ext-commands.js',c+'ext-contextMenus.js',c+'ext-desktop-runtime.js',c+'ext-devtools-inspectedWindow.js',
	c+'ext-devtools-network.js',c+'ext-devtools-panels.js',c+'ext-devtools.js',c+'ext-find.js',c+'ext-geckoProfiler.js',c+'ext-history.js',
	c+'ext-menus.js',c+'ext-omnibox.js',c+'ext-pageAction.js',c+'ext-pkcs11.js',c+'ext-sessions.js',c+'ext-sidebarAction.js',c+'ext-tabs.js',
	c+'ext-theme.js',c+'ext-url-overrides.js',c+'ext-utils.js',c+'ext-windows.js',c+'feeds/subscribe.js',c+'loop/js/client.js',
	c+'loop/js/contacts.js',c+'loop/js/conversation.js',c+'loop/js/conversationAppStore.js',c+'loop/js/conversationViews.js',
	c+'loop/js/desktopRouter.js',c+'loop/js/feedbackViews.js',c+'loop/js/otconfig.js',c+'loop/js/panel.js',c+'loop/js/roomStore.js',
	c+'loop/js/roomViews.js',c+'loop/libs/l10n.js',c+'loop/libs/sdk.js',c+'loop/sdk-content/js/dynamic_config.min.js',cl+'js/actions.js',
	cl+'js/activeRoomStore.js',cl+'js/conversationStore.js',cl+'js/dispatcher.js',cl+'js/feedbackApiClient.js',cl+'js/feedbackStore.js',
	cl+'js/feedbackViews.js',cl+'js/fxOSActiveRoomStore.js',cl+'js/linkifiedTextView.js',cl+'js/mixins.js',cl+'js/models.js',
	cl+'js/otSdkDriver.js',cl+'js/roomStates.js',cl+'js/roomStore.js',cl+'js/router.js',cl+'js/store.js',cl+'js/textChatStore.js',
	cl+'js/textChatView.js',cl+'js/urlRegExps.js',cl+'js/utils.js',cl+'js/validate.js',cl+'js/views.js',cl+'js/websocket.js',
	cl+'libs/backbone-1.1.2.js',cl+'libs/backbone-1.2.1.js',cl+'libs/jquery-2.1.0.js',cl+'libs/jquery-2.1.4.js',cl+'libs/lodash-2.4.1.js',
	cl+'libs/lodash-3.9.3.js',cl+'libs/react-0.10.0.js',cl+'libs/react-0.11.1.js',cl+'libs/react-0.11.2.js',cl+'libs/react-0.12.2.js',
	c+'migration/migration.js',c+'newtab/newTab.js',c+'newtab/preloaderContent.js',c+'nsContextMenu.js',c+'pageinfo/feeds.js',
	c+'pageinfo/pageInfo.js',c+'pageinfo/permissions.js',c+'pageinfo/security.js',cr+'ext-bookmarks.js',cr+'ext-browser.js',
	cr+'ext-browserAction.js',cr+'ext-browsingData.js',cr+'ext-chrome-settings-overrides.js',cr+'ext-commands.js',
	cr+'ext-devtools-inspectedWindow.js',cr+'ext-devtools-network.js',cr+'ext-devtools-panels.js',cr+'ext-devtools.js',cr+'ext-find.js',
	cr+'ext-geckoProfiler.js',cr+'ext-history.js',cr+'ext-menus.js',cr+'ext-omnibox.js',cr+'ext-pageAction.js',cr+'ext-pkcs11.js',
	cr+'ext-sessions.js',cr+'ext-sidebarAction.js',cr+'ext-tabs.js',cr+'ext-url-overrides.js',cr+'ext-windows.js',c+'places/bookmarkProperties.js',
	c+'places/bookmarksSidebar.js',c+'places/browserPlacesViews.js',c+'places/controller.js',c+'places/editBookmark.js',
	c+'places/editBookmarkOverlay.js',c+'places/history-panel.js',c+'places/historySidebar.js',c+'places/moveBookmarks.js',
	c+'places/places.js',c+'places/treeView.js',c+'pocket/main.js',cq+'js/dictionary.js',cq+'js/messages.js',cq+'js/saved.js',
	cq+'js/signup.js',cq+'js/tmpl.js',cq+'js/vendor/handlebars.runtime.js',cq+'js/vendor/jquery-2.1.1.min.js',
	cq+'js/vendor/jquery.tokeninput.min.js',c+'pocket/pktApi.js',cp+'aboutPermissions.js',cp+'advanced.js',cp+'applicationManager.js',
	cp+'applications.js',cp+'blocklists.js',cp+'clearSiteData.js',cp+'colors.js',cp+'connection.js',cp+'containers.js',cp+'content.js',
	cp+'cookies.js',cp+'fonts.js',ci+'-new/advanced.js',ci+'-new/applications.js',ci+'-new/containers.js',ci+'-new/findInPage.js',
	ci+'-new/main.js',ci+'-new/preferences.js',ci+'-new/privacy.js',ci+'-new/search.js',ci+'-new/subdialogs.js',ci+'-new/sync.js',
	ci+'/advanced.js',ci+'/applications.js',ci+'/containers.js',ci+'/content.js',ci+'/extensionControlled.js',ci+'/findInPage.js',
	ci+'/home.js',ci+'/main.js',ci+'/preferences.js',ci+'/privacy.js',ci+'/search.js',ci+'/security.js',ci+'/subdialogs.js',ci+'/sync.js',
	ci+'/syncDisconnect.js',cp+'languages.js',cp+'main.js',cp+'permissions.js',cp+'preferences.js',cp+'privacy.js',cp+'sanitize.js',
	cp+'search.js',cp+'security.js',cp+'selectBookmark.js',cp+'siteDataRemoveSelected.js',cp+'siteDataSettings.js',cp+'sitePermissions.js',
	cp+'sync.js',cp+'tabs.js',cp+'translation.js',c+'readinglist/sidebar.js',c+'remote-newtab/newTab.js',c+'safeMode.js',c+'sanitize.js',
	c+'sanitizeDialog.js',c+'search/engineManager.js',c+'search/searchReset.js',c+'searchSuggestionUI.js',c+'setDesktopBackground.js',
	c+'social-content.js',c+'sync/aboutSyncTabs.js',c+'sync/addDevice.js',c+'sync/customize.js',c+'sync/genericChange.js',c+'sync/progress.js',
	c+'sync/quota.js',c+'sync/setup.js',c+'sync/utils.js',c+'syncedtabs/sidebar.js',c+'tab-content.js',c+'tabbrowser.js',c+'tabview-content.js',
	c+'tabview.js',c+'utilityOverlay.js',c+'web-panels.js',c+'webext-panels.js',c+'webrtcIndicator.js',g+'BrowserElementChild.js',
	g+'BrowserElementChildPreload.js',g+'BrowserElementCopyPaste.js',g+'BrowserElementPanning.js',g+'BrowserElementPanningAPZDisabled.js',
	g+'PushServiceChildPreload.js',g+'TopLevelVideoDocument.js',g+'XPCNativeWrapper.js',g+'about.js',g+'aboutAbout.js',g+'aboutCache.js',
	g+'aboutCheckerboard.js',g+'aboutCompartments.js',g+'aboutMedia.js',g+'aboutMemory.js',g+'aboutNetworking.js',g+'aboutPerformance.js',
	g+'aboutProfiles.js',g+'aboutRights.js',g+'aboutServiceWorkers.js',g+'aboutSupport.js',g+'aboutTelemetry.js',g+'aboutUrlClassifier.js',
	g+'aboutwebrtc/aboutWebrtc.js',g+'accessibility/content-script.js',g+'alerts/alert.js',g+'appPicker.js',g+'backgroundPageThumbsContent.js',
	g+'bindings/calendar.js',g+'bindings/datekeeper.js',g+'bindings/datepicker.js',g+'bindings/spinner.js',g+'bindings/timekeeper.js',
	g+'bindings/timepicker.js',g+'browser-child.js',g+'browser-content.js',g+'charsetOverlay.js',g+'commonDialog.js',g+'config.js',g+'console.js',
	g+'content-HybridContentTelemetry.js',g+'contentAreaUtils.js',g+'crashes.js',g+'customElements.js',g+'customizeCharset.js',
	g+'customizeToolbar.js',g+'dialogOverlay.js',g+'editMenuOverlay.js',g+'elements/general.js',g+'elements/stringbundle.js',g+'extensions.js',
	g+'filepicker.js',g+'findUtils.js',g+'finddialog.js',g+'forms.js',g+'globalOverlay.js',g+'inlineSpellCheckUI.js',g+'l10n.js',
	g+'macWindowMenu.js',g+'manifestMessages.js',g+'nsClipboard.js',g+'nsDragAndDrop.js',g+'nsUserSettings.js',g+'post-fork-preload.js',
	g+'preferencesBindings.js',g+'preload.js',g+'printPageSetup.js',g+'printPreviewProgress.js',g+'printProgress.js',g+'printUtils.js',
	g+'printdialog.js',g+'printjoboptions.js',g+'process-content.js',g+'reader/JSDOMParser.js',g+'reader/Readability.js',g+'reader/aboutReader.js',
	g+'reader/readerWorker.js',g+'remote-test-ipc.js',g+'resetProfile.js',g+'select-child.js',g+'selectDialog.js',g+'strres.js',
	g+'test-ipcbrowser-chrome.js',g+'test-ipcbrowser-content.js',g+'treeUtils.js',g+'viewPartialSource.js',g+'viewSource-content.js',
	g+'viewSource.js',g+'viewSourceUtils.js',g+'viewZoomOverlay.js'
	];

	let imgUris = [b+'about-logo.png',b+'about-logo@2x.png',b+'about-wordmark.png',
	b+'about-wordmark.svg',b+'about.png',b+'icon128.png',b+'icon16.png',b+'icon32.png',b+'icon48.png',
	b+'icon64.png',b+'identity-icons-brand.png',b+'identity-icons-brand.svg',
	b+'identity-icons-brand@2x.png',b+'silhouette-40.svg',c+'aboutRobots-icon.png',
	c+'aboutRobots-widget-left.png',c+'aboutaccounts/images/fox.png',
	c+'aboutaccounts/images/graphic_sync_intro.png',c+'aboutaccounts/images/graphic_sync_intro@2x.png',
	ca+'addons.png',ca+'addons@2x.png',ca+'apps.png',ca+'apps@2x.png',ca+'bookmarks.png',
	ca+'bookmarks@2x.png',ca+'downloads.png',ca+'downloads@2x.png',ca+'history.png',ca+'history@2x.png',
	ca+'mozilla.png',ca+'mozilla.svg',ca+'mozilla@2x.png',ca+'restore-large.png',
	ca+'restore-large@2x.png',ca+'restore.png',ca+'restore@2x.png',ca+'settings.png',
	ca+'settings@2x.png',ca+'snippet1.png',ca+'snippet1@2x.png',ca+'snippet2.png',ca+'snippet2@2x.png',
	ca+'sync.png',ca+'sync@2x.png',c+'aboutneterror/alert.svg',c+'aboutneterror/info.svg',
	c+'default-theme-icon.svg',ct+'1.footer.jpg',ct+'1.header.jpg',ct+'1.icon.jpg',ct+'1.preview.jpg',
	ct+'2.footer.jpg',ct+'2.header.jpg',ct+'2.icon.jpg',ct+'2.preview.jpg',ct+'3.footer.png',
	ct+'3.header.png',ct+'3.icon.png',ct+'3.preview.png',ct+'4.footer.png',ct+'4.header.png',
	ct+'4.icon.png',ct+'4.preview.png',ct+'5.footer.png',ct+'5.header.png',ct+'5.icon.jpg',
	ct+'5.preview.jpg',ct+'compact.header.png',ct+'compactdark.icon.svg',ct+'compactlight.icon.svg',
	ct+'dark.icon.svg',ct+'devedition.header.png',ct+'devedition.icon.png',ct+'light.icon.svg',
	cd+'framework/dev-edition-logo.png',cd+'profiler/cleopatra/images/circlearrow.svg',
	cd+'profiler/cleopatra/images/noise.png',cd+'profiler/cleopatra/images/throbber.svg',
	cd+'profiler/cleopatra/images/treetwisty.svg',c+'extension.svg',c+'gcli_sec_bad.svg',c+'gcli_sec_good.svg',
	c+'gcli_sec_moderate.svg',c+'history-swipe-arrow.svg',c+'illustrations/error-connection-failure.svg',
	c+'illustrations/error-malformed-url.svg',c+'illustrations/error-server-not-found.svg',
	c+'illustrations/under-construction.svg',c+'loop/sdk-content/images/rtc/access-denied-chrome.png',
	c+'loop/sdk-content/images/rtc/access-denied-copy-firefox.png',c+'loop/sdk-content/images/rtc/access-denied-firefox.png',
	c+'loop/sdk-content/images/rtc/access-predenied-chrome.png',c+'loop/sdk-content/images/rtc/access-prompt-chrome.png',
	c+'loop/sdk-content/images/rtc/audioonly-publisher.png',c+'loop/sdk-content/images/rtc/audioonly-subscriber.png',
	c+'loop/sdk-content/images/rtc/buttons.png',c+'loop/sdk-content/images/rtc/mic-off.png',c+'loop/sdk-content/images/rtc/mic-on.png',
	c+'loop/sdk-content/images/rtc/speaker-off.png',c+'loop/sdk-content/images/rtc/speaker-on.png',cl+'img/02.png',
	cl+'img/02@2x.png',cl+'img/animated-spinner.svg',cl+'img/audio-call-avatar.svg',
	cl+'img/audio-inverse-14x14.png',cl+'img/audio-inverse-14x14@2x.png',cl+'img/avatars.svg',
	cl+'img/beta-ribbon.svg',cl+'img/chatbubble-arrow-left.svg',cl+'img/chatbubble-arrow-right.svg',
	cl+'img/check.svg',cl+'img/dropdown-inverse.png',cl+'img/dropdown-inverse@2x.png',
	cl+'img/ellipsis-v.svg',cl+'img/empty_contacts.svg',cl+'img/empty_conversations.svg',
	cl+'img/empty_search.svg',cl+'img/facemute-14x14.png',cl+'img/facemute-14x14@2x.png',
	cl+'img/firefox-avatar.svg',cl+'img/hangup-inverse-14x14.png',cl+'img/hangup-inverse-14x14@2x.png',
	cl+'img/happy.png',cl+'img/hello_logo.svg',cl+'img/helloicon.svg',cl+'img/icon_32.png',
	cl+'img/icon_64.png',cl+'img/icons-10x10.svg',cl+'img/icons-14x14.svg',cl+'img/icons-16x16.svg',
	cl+'img/movistar.png',cl+'img/movistar@2x.png',cl+'img/mute-inverse-14x14.png',
	cl+'img/mute-inverse-14x14@2x.png',cl+'img/sad.png',cl+'img/sad_hello_icon_64x64.svg',
	cl+'img/spinner.png',cl+'img/spinner.svg',cl+'img/spinner@2x.png',cl+'img/svg/audio-hover.svg',
	cl+'img/svg/audio-mute-hover.svg',cl+'img/svg/audio-mute.svg',cl+'img/svg/audio.svg',
	cl+'img/svg/exit.svg',cl+'img/svg/glyph-account-16x16.svg',cl+'img/svg/glyph-email-16x16.svg',
	cl+'img/svg/glyph-facebook-16x16.svg',cl+'img/svg/glyph-help-16x16.svg',cl+'img/svg/glyph-link-16x16.svg',
	cl+'img/svg/glyph-settings-16x16.svg',cl+'img/svg/glyph-signin-16x16.svg',cl+'img/svg/glyph-signout-16x16.svg',
	cl+'img/svg/glyph-user-16x16.svg',cl+'img/svg/media-group-left-hover.svg',cl+'img/svg/media-group-right-hover.svg',
	cl+'img/svg/media-group.svg',cl+'img/svg/settings-hover.svg',cl+'img/svg/settings.svg',
	cl+'img/svg/sharing-active.svg',cl+'img/svg/sharing-hover.svg',cl+'img/svg/sharing-pending.svg',
	cl+'img/svg/sharing.svg',cl+'img/svg/video-hover.svg',cl+'img/svg/video-mute-hover.svg',
	cl+'img/svg/video-mute.svg',cl+'img/svg/video.svg',cl+'img/telefonica.png',cl+'img/telefonica@2x.png',
	cl+'img/video-inverse-14x14.png',cl+'img/video-inverse-14x14@2x.png',cl+'img/vivo.png',
	cl+'img/vivo@2x.png',c+'microsoft-translator-attribution.png',cq+'img/pocketerror@1x.png',
	cq+'img/pocketerror@2x.png',cq+'img/pocketlogo@1x.png',cq+'img/pocketlogo@2x.png',
	cq+'img/pocketlogosolo@1x.png',cq+'img/pocketlogosolo@2x.png',cq+'img/pocketmenuitem16.png',
	cq+'img/pocketmenuitem16@2x.png',cq+'img/pocketsignup_button@1x.png',cq+'img/pocketsignup_button@2x.png',
	cq+'img/pocketsignup_devices@1x.png',cq+'img/pocketsignup_devices@2x.png',cq+'img/pocketsignup_hero@1x.png',
	cq+'img/pocketsignup_hero@2x.png',cq+'img/signup_firefoxlogo@1x.png',cq+'img/signup_firefoxlogo@2x.png',
	cq+'img/signup_help@1x.png',cq+'img/signup_help@2x.png',cq+'img/tag_close@1x.png',
	cq+'img/tag_close@2x.png',cq+'img/tag_closeactive@1x.png',cq+'img/tag_closeactive@2x.png',
	c+'static-robot.png',c+'usercontext-briefcase.svg',c+'usercontext-cart.svg',c+'usercontext-circle.svg',
	c+'usercontext-dollar.svg',c+'usercontext-fingerprint.svg',c+'usercontext.svg',s+'Geolocation-16.png',
	s+'Geolocation-16@2x.png',s+'Geolocation-64.png',s+'Geolocation-64@2x.png',s+'Info-XP.png',s+'Info.png',
	s+'KUI-background.png',s+'Metro_Glyph-inverted.png',s+'Metro_Glyph-menuPanel.png',s+'Metro_Glyph.png',
	s+'Privacy-16-XP.png',s+'Privacy-16.png',s+'Privacy-32.png',s+'Privacy-48.png',s+'Push-16.png',
	s+'Push-16@2x.png',s+'Push-64.png',s+'Push-64@2x.png',s+'Search.png',s+'Search@2x.png',s+'Secure-Glyph.png',
	s+'Secure-Glyph@2x.png',s+'Secure.png',s+'Secure24-XP.png',s+'Secure24.png',s+'Security-broken.png',
	s+'Toolbar-XP.png',s+'Toolbar-aero.png',s+'Toolbar-aero@2x.png',s+'Toolbar-background-noise.png',
	s+'Toolbar-inverted.png',s+'Toolbar-inverted@2x.png',s+'Toolbar-lunaSilver.png',s+'Toolbar-small.png',
	s+'Toolbar-win7.png',s+'Toolbar-win7@2x.png',s+'Toolbar-win8.png',s+'Toolbar-win8@2x.png',s+'Toolbar.png',
	s+'Toolbar@2x.png',s+'aboutCertError_sectionCollapsed-rtl.png',s+'aboutCertError_sectionCollapsed.png',
	s+'aboutCertError_sectionExpanded.png',s+'aboutNetError_alert.svg',s+'aboutNetError_info.svg',
	s+'aboutSessionRestore-window-icon.png',s+'accessibility-active.svg',s+'accessibility.svg',
	s+'actionicon-tab-XPVista7.png',s+'actionicon-tab.png',s+'actionicon-tab@2x.png',s+'addons.svg',
	s+'addons/addon-badge.svg',s+'addons/addon-install-anchor.svg',s+'addons/addon-install-blocked.svg',
	s+'addons/addon-install-confirm.svg',s+'addons/addon-install-downloading.svg',s+'addons/addon-install-error.svg',
	s+'addons/addon-install-installed.svg',s+'addons/addon-install-restart.svg',s+'addons/addon-install-warning.svg',
	s+'arrow-dropdown.svg',s+'arrow-left.svg',s+'back-12.svg',s+'back-large.svg',s+'back.svg',
	s+'bad-content-blocked-16.png',s+'bad-content-blocked-16@2x.png',s+'bad-content-blocked-64.png',
	s+'bad-content-blocked-64@2x.png',s+'bad-content-unblocked-16.png',s+'bad-content-unblocked-16@2x.png',
	s+'bad-content-unblocked-64.png',s+'bad-content-unblocked-64@2x.png',s+'badge-add-engine.png',
	s+'badge-add-engine@2x.png',s+'bookmark-animation.svg',s+'bookmark-hollow.svg',s+'bookmark-star-on-tray.svg',
	s+'bookmark.svg',s+'bookmarks-toolbar.svg',s+'bookmarksMenu.svg',s+'caption-buttons.svg',s+'cert-error.svg',
	s+'characterEncoding.svg',s+'check-animation.svg',s+'check.svg',s+'chevron-animation.svg',s+'chevron.svg',
	s+'click-to-play-warning-stripes.png',s+'compacttheme/loading-inverted.png',s+'compacttheme/loading-inverted@2x.png',
	s+'compacttheme/urlbar-history-dropmarker.svg',s+'connection-mixed-active-loaded.svg',
	s+'connection-mixed-passive-loaded.svg',s+'connection-secure.svg',s+'containers.svg',s+'content-contextmenu.svg',
	se+'arrow-subview-back.svg',se+'arrow-subview.svg',se+'conn-degraded.svg',se+'conn-not-secure.svg',
	se+'conn-secure.svg',se+'connection.svg',se+'extension.svg',se+'mcb-disabled.svg',se+'permissions.svg',
	se+'tracking-protection-disabled.svg',se+'tracking-protection.svg',se+'warning-gray.svg',se+'warning-yellow.svg',
	sc+'background-noise-toolbar.png',sc+'customize-illustration-rtl.png',sc+'customize-illustration-rtl@2x.png',
	sc+'customize-illustration.png',sc+'customize-illustration@2x.png',sc+'customize-titleBar-toggle.png',
	sc+'customize-titleBar-toggle@2x.png',sc+'customizeMode-gridTexture.png',sc+'customizeMode-separatorHorizontal.png',
	sc+'customizeMode-separatorVertical.png',sc+'density-compact.svg',sc+'density-normal.svg',
	sc+'density-touch.svg',sc+'empty-overflow-panel.png',sc+'empty-overflow-panel@2x.png',
	sc+'info-icon-customizeTip.png',sc+'info-icon-customizeTip@2x.png',sc+'menu-arrow.svg',
	sc+'menuPanel-customizeFinish.png',sc+'menuPanel-customizeFinish@2x.png',sc+'panelarrow-customizeTip.png',
	sc+'panelarrow-customizeTip@2x.png',sc+'subView-arrow-back-inverted-rtl.png',sc+'subView-arrow-back-inverted-rtl@2x.png',
	sc+'subView-arrow-back-inverted.png',sc+'subView-arrow-back-inverted@2x.png',sc+'thumburger-XP.png',
	sc+'thumburger-XP@2x.png',sc+'thumburger-aero.png',sc+'thumburger-aero@2x.png',
	sc+'thumburger-inverted.png',sc+'thumburger-inverted@2x.png',sc+'thumburger-lunaSilver.png',
	sc+'thumburger-lunaSilver@2x.png',sc+'thumburger-win8.png',sc+'thumburger-win8@2x.png',
	sc+'thumburger.png',sc+'thumburger@2x.png',sc+'whimsy-bw.png',sc+'whimsy-bw@2x.png',
	sc+'whimsy.png',sc+'whimsy@2x.png',s+'customize.svg',s+'devedition/search.svg',s+'devedition/urlbar-arrow.png',
	s+'devedition/urlbar-arrow@2x.png',s+'devedition/urlbar-history-dropmarker.svg',s+'developer.svg',s+'device-desktop.svg',
	s+'device-mobile.svg',s+'device-phone.svg',s+'device-tablet.svg',sd+'add.svg',sd+'alerticon-warning.png',
	sd+'alerticon-warning@2x.png',sd+'animation-fast-track.svg',sd+'app-manager/add.svg',sd+'app-manager/default-app-icon.png',
	sd+'app-manager/error.svg',sd+'app-manager/index-icons.svg',sd+'app-manager/noise.png',sd+'app-manager/plus.svg',
	sd+'app-manager/remove.svg',sd+'app-manager/rocket.svg',sd+'app-manager/warning.svg',sd+'arrow-e.png',
	sd+'arrow-e@2x.png',sd+'background-noise-toolbar.png',sd+'breadcrumbs-divider@2x.png',sd+'breadcrumbs-scrollbutton.png',
	sd+'breadcrumbs-scrollbutton@2x.png',sd+'close.png',sd+'close@2x.png',sd+'command-console.png',
	sd+'command-console@2x.png',sd+'command-eyedropper.png',sd+'command-eyedropper@2x.png',sd+'command-frames.png',
	sd+'command-frames@2x.png',sd+'command-paintflashing.png',sd+'command-paintflashing@2x.png',sd+'command-pick.png',
	sd+'command-pick@2x.png',sd+'command-responsivemode.png',sd+'command-responsivemode@2x.png',sd+'command-rulers.png',
	sd+'command-rulers@2x.png',sd+'command-scratchpad.png',sd+'command-scratchpad@2x.png',sd+'command-screenshot.png',
	sd+'command-screenshot@2x.png',sd+'command-tilt.png',sd+'command-tilt@2x.png',sd+'commandline-icon.png',
	sd+'commandline-icon@2x.png',sd+'controls.png',sd+'controls@2x.png',sd+'cubic-bezier-swatch.png',
	sd+'cubic-bezier-swatch@2x.png',sd+'debugger-blackbox-eye.png',sd+'debugger-blackbox.png',sd+'debugger-blackbox@2x.png',
	sd+'debugger-collapse.png',sd+'debugger-collapse@2x.png',sd+'debugger-expand.png',sd+'debugger-expand@2x.png',
	sd+'debugger-pause.png',sd+'debugger-pause@2x.png',sd+'debugger-play.png',sd+'debugger-play@2x.png',
	sd+'debugger-prettyprint.png',sd+'debugger-prettyprint@2x.png',sd+'debugger-step-in.png',sd+'debugger-step-in@2x.png',
	sd+'debugger-step-out.png',sd+'debugger-step-out@2x.png',sd+'debugger-step-over.png',sd+'debugger-step-over@2x.png',
	sd+'debugger-toggleBreakpoints.png',sd+'debugger-toggleBreakpoints@2x.png',sd+'dock-bottom-maximize@2x.png',
	sd+'dock-bottom-minimize@2x.png',sd+'dock-bottom@2x.png',sd+'dock-side@2x.png',sd+'dropmarker.png',
	sd+'dropmarker.svg',sd+'editor-breakpoint.png',sd+'editor-breakpoint@2x.png',sd+'editor-debug-location.png',
	sd+'editor-debug-location@2x.png',sd+'editor-error.png',sd+'fast-forward.png',sd+'fast-forward@2x.png',
	sd+'filetype-dir-close.svg',sd+'filetype-dir-open.svg',sd+'filetype-globe.svg',sd+'filetype-store.svg',
	sd+'filter-swatch.svg',sd+'filters.svg',sd+'itemArrow-dark-ltr.png',sd+'itemArrow-dark-ltr.svg',
	sd+'itemArrow-dark-rtl.png',sd+'itemArrow-dark-rtl.svg',sd+'itemArrow-ltr.svg',sd+'itemArrow-rtl.svg',
	sd+'itemToggle-light.png',sd+'itemToggle.png',sd+'itemToggle@2x.png',sd+'layout-background-grid.png',
	sd+'magnifying-glass-light.png',sd+'magnifying-glass-light@2x.png',sd+'magnifying-glass.png',sd+'magnifying-glass@2x.png',
	sd+'newtab-inverted.png',sd+'newtab-inverted@2x.png',sd+'newtab.png',sd+'newtab@2x.png',
	sd+'noise.png',sd+'option-icon.png',sd+'performance-icons.svg',sd+'power.svg',
	sd+'profiler-stopwatch-checked.svg',sd+'profiler-stopwatch.png',sd+'profiler-stopwatch.svg',
	sd+'projecteditor/file-icons-sheet@2x.png',sd+'pseudo-class.svg',sd+'responsive-background.png',
	sd+'responsive-horizontal-resizer.png',sd+'responsive-horizontal-resizer@2x.png',sd+'responsive-se-resizer.png',
	sd+'responsive-se-resizer@2x.png',sd+'responsive-vertical-resizer.png',sd+'responsive-vertical-resizer@2x.png',
	sd+'responsiveui-home.png',sd+'responsiveui-rotate.png',sd+'responsiveui-rotate@2x.png',sd+'responsiveui-screenshot.png',
	sd+'responsiveui-screenshot@2x.png',sd+'responsiveui-touch.png',sd+'responsiveui-touch@2x.png',sd+'rewind.png',
	sd+'rewind@2x.png',sd+'search-clear-dark.svg',sd+'search-clear-failed.svg',sd+'search-clear-light.svg',
	sd+'timeline-filter.svg',sd+'toggle-tools.png',sd+'toggle-tools@2x.png',sd+'tool-debugger-paused.svg',
	sd+'tool-debugger.svg',sd+'tool-inspector.svg',sd+'tool-network.svg',sd+'tool-options.svg',
	sd+'tool-profiler-active.svg',sd+'tool-profiler.svg',sd+'tool-scratchpad.svg',sd+'tool-shadereditor.svg',
	sd+'tool-storage.svg',sd+'tool-styleeditor.svg',sd+'tool-webaudio.svg',sd+'tool-webconsole.svg',
	sd+'tooltip/arrow-horizontal-dark.png',sd+'tooltip/arrow-horizontal-dark@2x.png',sd+'tooltip/arrow-horizontal-light.png',
	sd+'tooltip/arrow-horizontal-light@2x.png',sd+'tooltip/arrow-vertical-dark.png',sd+'tooltip/arrow-vertical-dark@2x.png',
	sd+'tooltip/arrow-vertical-light.png',sd+'tooltip/arrow-vertical-light@2x.png',sd+'tracer-icon.png',sd+'tracer-icon@2x.png',
	sd+'undock@2x.png',sd+'vview-delete.png',sd+'vview-delete@2x.png',sd+'vview-edit.png',
	sd+'vview-edit@2x.png',sd+'vview-lock.png',sd+'vview-lock@2x.png',sd+'vview-open-inspector.png',
	sd+'vview-open-inspector@2x.png',sd+'webconsole.png',sd+'webconsole.svg',sd+'webconsole@2x.png',
	s+'dots.png',s+'dots@2x.png',s+'download.svg',sf+'buttons-XP.png',sf+'buttons.png',
	sf+'buttons@2x.png',sf+'download-blocked.svg',sf+'download-glow-XPVista7.png',sf+'download-glow-menuPanel-XPVista7.png',
	sf+'download-glow-menuPanel-win7.png',sf+'download-glow-menuPanel.png',sf+'download-glow-menuPanel@2x.png',
	sf+'download-glow.png',sf+'download-glow@2x.png',sf+'download-icons.svg',sf+'download-notification-finish.png',
	sf+'download-notification-finish@2x.png',sf+'download-notification-start.png',sf+'download-notification-start@2x.png',
	sf+'download-summary.png',sf+'download-summary.svg',sf+'download-summary@2x.png',sf+'menubutton-dropmarker.svg',
	sf+'notification-start-animation.svg',s+'drm-icon.svg',s+'e10s-64@2x.png',s+'edit-copy.svg',s+'edit-cut.svg',
	s+'edit-paste.svg',s+'email-link.svg',s+'favicon-search-16.svg',s+'feed.svg',s+'feeds/audioFeedIcon.png',
	s+'feeds/audioFeedIcon16.png',s+'feeds/feedIcon-XP.png',s+'feeds/feedIcon.png',s+'feeds/feedIcon16-XP.png',s+'feeds/feedIcon16.png',
	s+'feeds/videoFeedIcon.png',s+'feeds/videoFeedIcon16.png',s+'filters.svg',s+'find.svg',s+'folder.svg',s+'forget.svg',
	s+'forward.svg',s+'fullscreen-darknoise.png',s+'fullscreen-enter.svg',s+'fullscreen-exit.svg',s+'fullscreen.svg',
	s+'fullscreen/insecure.svg',s+'fullscreen/secure.svg',s+'fxa/android.png',s+'fxa/android@2x.png',s+'fxa/default-avatar.png',
	s+'fxa/default-avatar.svg',s+'fxa/default-avatar@2x.png',s+'fxa/default-profile-image.svg',s+'fxa/ios.png',s+'fxa/ios@2x.png',
	s+'fxa/logo.png',s+'fxa/logo@2x.png',s+'fxa/sync-illustration-issue.svg',s+'fxa/sync-illustration.png',s+'fxa/sync-illustration.svg',
	s+'fxa/sync-illustration@2x.png',s+'gear.svg',s+'heartbeat-icon.svg',s+'heartbeat-star-lit.svg',s+'heartbeat-star-off.svg',
	s+'help.svg',s+'history.svg',s+'home.svg',s+'icon-search-64.svg',s+'identity-XP.png',s+'identity-icon-hover.svg',
	s+'identity-icon-notice-hover.svg',s+'identity-icon-notice.svg',s+'identity-icon.svg',s+'identity-icons-generic.png',
	s+'identity-icons-generic@2x.png',s+'identity-icons-https-ev.png',s+'identity-icons-https-ev@2x.png',s+'identity-icons-https-mixed-active.png',
	s+'identity-icons-https-mixed-active@2x.png',s+'identity-icons-https-mixed-display.png',s+'identity-icons-https-mixed-display@2x.png',
	s+'identity-icons-https.png',s+'identity-icons-https@2x.png',s+'identity-mixed-active-blocked.svg',s+'identity-mixed-active-loaded.svg',
	s+'identity-mixed-passive-loaded.svg',s+'identity-not-secure.svg',s+'identity-secure.svg',s+'identity.png',s+'identity@2x.png',
	s+'illustrations/error-session-restore.svg',s+'info.svg',s+'keyhole-circle.png',s+'keyhole-circle@2x.png',s+'keyhole-forward-mask.svg',
	s+'library-bookmark-animation.svg',s+'library.svg',s+'link.svg',s+'lion/places/toolbar.png',s+'lion/tabbrowser/alltabs-box-bkgnd-icon.png',
	s+'lion/tabview/tabview.png',s+'lion/toolbarbutton-dropmarker.png',s+'livemark-folder-XP.png',s+'livemark-folder.png',
	s+'loop/menuPanel-aero.png',s+'loop/menuPanel-aero@2x.png',s+'loop/menuPanel.png',s+'loop/menuPanel@2x.png',s+'loop/toolbar-XP.png',
	s+'loop/toolbar-XP@2x.png',s+'loop/toolbar-aero.png',s+'loop/toolbar-aero@2x.png',s+'loop/toolbar-inverted.png',
	s+'loop/toolbar-inverted@2x.png',s+'loop/toolbar-lunaSilver.png',s+'loop/toolbar-lunaSilver@2x.png',s+'loop/toolbar-win8.png',
	s+'loop/toolbar-win8@2x.png',s+'loop/toolbar.png',s+'loop/toolbar@2x.png',s+'magnifier.png',s+'magnifier@2px.png',
	s+'magnifier@2x.png',s+'mail.svg',s+'mask.png',s+'mask@2x.png',s+'menu-back-XP.png',s+'menu-back.png',
	s+'menu-badged.svg',s+'menu-forward-XP.png',s+'menu-forward.png',s+'menu.svg',s+'menuPanel-aero.png',
	s+'menuPanel-aero@2x.png',s+'menuPanel-customize.png',s+'menuPanel-customize@2x.png',s+'menuPanel-exit.png',s+'menuPanel-exit@2x.png',
	s+'menuPanel-help.png',s+'menuPanel-help@2x.png',s+'menuPanel-small-aero.png',s+'menuPanel-small-aero@2x.png',s+'menuPanel-small.png',
	s+'menuPanel-small.svg',s+'menuPanel-small@2x.png',s+'menuPanel.png',s+'menuPanel.svg',s+'menuPanel@2x.png',
	s+'mixed-content-blocked-16.png',s+'mixed-content-blocked-64.png',s+'monitor.png',s+'monitor_16-10.png',s+'new-tab.svg',
	s+'new-window.svg',s+'newtab/close.png',s+'newtab/controls.png',s+'newtab/controls.svg',s+'newtab/whimsycorn.png',
	s+'notification-16.png',s+'notification-16@2x.png',s+'notification-64.png',s+'notification-64@2x.png',s+'notification-icons.svg',
	sn+'autoplay-media-blocked.svg',sn+'autoplay-media.svg',sn+'camera-blocked.svg',sn+'camera.svg',sn+'canvas-blocked.svg',
	sn+'canvas.svg',sn+'default-info.svg',sn+'desktop-notification-blocked.svg',sn+'desktop-notification.svg',
	sn+'focus-tab-by-prompt.svg',sn+'geo-blocked.svg',sn+'geo-detailed.svg',sn+'geo.svg',sn+'indexedDB-blocked.svg',
	sn+'indexedDB.svg',sn+'login-detailed.svg',sn+'login.svg',sn+'microphone-blocked.svg',sn+'microphone-detailed.svg',
	sn+'microphone.svg',sn+'midi.svg',sn+'persistent-storage-blocked.svg',sn+'persistent-storage.svg',sn+'plugin-badge.svg',
	sn+'plugin-blocked.svg',sn+'plugin.svg',sn+'popup-subitem.svg',sn+'popup.svg',sn+'screen-blocked.svg',sn+'screen.svg',sn+'update.svg',
	sn+'webauthn.svg',s+'notification-pluginAlert.png',s+'notification-pluginAlert@2x.png',s+'notification-pluginBlocked.png',
	s+'notification-pluginBlocked@2x.png',s+'notification-pluginNormal.png',s+'notification-pluginNormal@2x.png',s+'open.svg',
	s+'page-action.svg',s+'page-livemarks.png',s+'page-livemarks@2x.png',s+'pageInfo-XP.png',s+'pageInfo.png',
	s+'panel-expander-closed.png',s+'panel-expander-closed@2x.png',s+'panel-expander-open.png',s+'panel-expander-open@2x.png',
	s+'panel-icon-arrow-left.svg',s+'panel-icon-arrow-right.svg',s+'panel-icon-cancel.svg',s+'panel-icon-folder.svg',
	s+'panel-icon-magnifier.svg',s+'panel-icon-retry.svg',s+'panel-icons.svg',s+'panel-plus-sign.png',s+'panic-panel/header-small.png',
	s+'panic-panel/header-small@2x.png',s+'panic-panel/header.png',s+'panic-panel/header@2x.png',s+'panic-panel/icons.png',
	s+'panic-panel/icons@2x.png',sq+'allBookmarks-XP.png',sq+'allBookmarks.png',sq+'autocomplete-star-XPVista7.png',
	sq+'autocomplete-star.png',sq+'autocomplete-star@2x.png',sq+'bookmark-XP.png',sq+'bookmark.png',sq+'bookmarks-menu-arrow.png',
	sq+'bookmarks-notification-finish.png',sq+'bookmarks-notification-finish@2x.png',sq+'bookmarksMenu-XP.png',sq+'bookmarksMenu.png',
	sq+'bookmarksMenu.svg',sq+'bookmarksToolbar-XP.png',sq+'bookmarksToolbar-menuPanel-XP.png',sq+'bookmarksToolbar-menuPanel.png',
	sq+'bookmarksToolbar-menuPanel@2x.png',sq+'bookmarksToolbar.png',sq+'bookmarksToolbar.svg',sq+'bookmarksToolbar@2x.png',
	sq+'calendar-XP.png',sq+'calendar.png',sq+'downloads.png',sq+'expander-closed-active.png',
	sq+'expander-closed.png',sq+'expander-open-active.png',sq+'expander-open.png',sq+'folder-live.svg',
	sq+'folder-smart.svg',sq+'folder.svg',sq+'folderDropArrow.png',sq+'folderDropArrow@2x.png',
	sq+'history-XP.png',sq+'history.png',sq+'history.svg',sq+'history@2x.png',sq+'libraryToolbar-XP.png',
	sq+'libraryToolbar.png',sq+'livemark-item.png',sq+'minus-active.png',sq+'minus.png',sq+'plus-active.png',
	sq+'plus.png',sq+'query-XP.png',sq+'query.png',sq+'query@2x.png',sq+'star-icons.png',
	sq+'star-icons@2x.png',sq+'starred48-XP.png',sq+'starred48.png',sq+'starred48@2x.png',sq+'tag-XP.png',
	sq+'tag.png',sq+'tag.svg',sq+'tag@2x.png',sq+'toolbar.png',sq+'toolbarDropMarker-XP.png',
	sq+'toolbarDropMarker.png',sq+'unfiledBookmarks.png',sq+'unfiledBookmarks.svg',sq+'unfiledBookmarks@2x.png',
	sq+'unsortedBookmarks-XP.png',sq+'unsortedBookmarks.png',sq+'unstarred48.png',s+'pluginInstall-16.png',
	s+'pluginInstall-16@2x.png',s+'pluginInstall-64.png',s+'pluginInstall-64@2x.png',s+'pointerLock-16.png',s+'pointerLock-16@2x.png',
	s+'pointerLock-64.png',s+'pointerLock-64@2x.png',sp+'Options-XP.png',sp+'Options-sync.png',
	sp+'Options.png',sp+'alwaysAsk-XP.png',sp+'alwaysAsk.png',sp+'application-XP.png',
	sp+'application.png',sp+'checkbox-aero.png',sp+'checkbox-classic.png',sp+'checkbox-xp.png',
	sp+'checkbox.png',sp+'checkbox@2x.png',sp+'in-content-new/icons.svg',sp+'in-content-new/search-arrow-indicator.svg',
	sp+'in-content/check.png',sp+'in-content/check@2x.png',sp+'in-content/critters-postcard.jpg',
	sp+'in-content/default-profile-image.svg',sp+'in-content/dropdown-disabled.png',sp+'in-content/dropdown-disabled@2x.png',
	sp+'in-content/dropdown.png',sp+'in-content/dropdown@2x.png',sp+'in-content/face-sad.svg',
	sp+'in-content/face-smile.svg',sp+'in-content/fxa-avatar.svg',sp+'in-content/general.svg',sp+'in-content/header.png',
	sp+'in-content/header@2x.png',sp+'in-content/help-glyph.png',sp+'in-content/help-glyph@2x.png',
	sp+'in-content/icons.png',sp+'in-content/icons.svg',sp+'in-content/icons@2x.png',sp+'in-content/logo-android.svg',
	sp+'in-content/logo-ios.svg',sp+'in-content/no-search-bar.svg',sp+'in-content/no-search-results.svg',
	sp+'in-content/privacy-security.svg',sp+'in-content/search-arrow-indicator.svg',sp+'in-content/search-bar.svg',
	sp+'in-content/search.svg',sp+'in-content/sorter.png',sp+'in-content/sorter@2x.png',sp+'in-content/sync-devices.svg',
	sp+'in-content/sync.svg',sp+'mail-XP.png',sp+'mail.png',sp+'saveFile-XP.png',
	sp+'saveFile.png',s+'print.svg',s+'private-browsing.svg',s+'privateBrowsing.svg',s+'privatebrowsing-mask-short.png',
	s+'privatebrowsing-mask-short@2x.png',s+'privatebrowsing-mask-tabstrip-XPVista7.png',s+'privatebrowsing-mask-tabstrip-win7.png',
	s+'privatebrowsing-mask-tabstrip.png',s+'privatebrowsing-mask-titlebar-XPVista7-tall.png',s+'privatebrowsing-mask-titlebar-XPVista7.png',
	s+'privatebrowsing-mask-titlebar-win7-tall.png',s+'privatebrowsing-mask-titlebar-win7.png',s+'privatebrowsing-mask-titlebar.png',s+'privatebrowsing-mask.png',
	s+'privatebrowsing-mask@2x.png',s+'privatebrowsing/attention.png',s+'privatebrowsing/attention@2x.png',s+'privatebrowsing/check.png',
	s+'privatebrowsing/check.svg',s+'privatebrowsing/check@2x.png',s+'privatebrowsing/favicon.svg',s+'privatebrowsing/mask.svg',
	s+'privatebrowsing/private-browsing.svg',s+'privatebrowsing/shield-page.png',s+'privatebrowsing/shield-page@2x.png',
	s+'privatebrowsing/tracking-protection-off.svg',s+'privatebrowsing/tracking-protection.svg',s+'quit.svg',s+'reader-tour.png',
	s+'reader-tour@2x.png',s+'readerMode.svg',s+'readinglist/icons.svg',s+'readinglist/readinglist-icon.svg',s+'reload-stop-go-XPVista7.png',
	s+'reload-stop-go-XPVista7@2x.png',s+'reload-stop-go-preWin10.png',s+'reload-stop-go-preWin10@2x.png',s+'reload-stop-go-win7.png',
	s+'reload-stop-go-win7@2x.png',s+'reload-stop-go.png',s+'reload-stop-go@2x.png',s+'reload-to-stop.svg',s+'reload.svg',
	s+'restore-session.svg',s+'save.svg',s+'search-arrow-go.svg',s+'search-engine-placeholder.png',s+'search-engine-placeholder@2x.png',
	s+'search-glass.svg',s+'search-history-icon.svg',s+'search-indicator-add-engine.png',s+'search-indicator-add-engine@2x.png',
	s+'search-indicator-badge-add.png',s+'search-indicator-badge-add.svg',s+'search-indicator-badge-add@2x.png',s+'search-indicator-magnifying-glass.svg',
	s+'search-indicator.png',s+'search-indicator@2x.png',s+'search-pref.png',s+'searchbar-dropdown-arrow-XP.png',
	s+'searchbar-dropdown-arrow.png',s+'searchbar-dropmarker.png',s+'searchbar-dropmarker@2x.png',s+'send-to-device.svg',
	s+'session-restore.svg',s+'settings.svg',s+'share.svg',s+'sidebar/close.svg',s+'sidebars-right.svg',s+'sidebars.svg',
	s+'slowStartup-16.png',s+'social/chat-icons.png',s+'social/chat-icons.svg',s+'social/gear_clicked.png',s+'social/gear_default.png',
	s+'social/services-16.png',s+'social/services-16@2x.png',s+'social/services-64.png',s+'social/services-64@2x.png',
	s+'social/share-button-active.png',s+'social/share-button.png',s+'stop-to-reload.svg',s+'stop.svg',s+'subtle-pattern.png',
	s+'sync-128.png',s+'sync-16.png',s+'sync-32.png',s+'sync-bg.png',s+'sync-desktopIcon.png',s+'sync-desktopIcon.svg',
	s+'sync-horizontalbar-XPVista7.png',s+'sync-horizontalbar-XPVista7@2x.png',s+'sync-horizontalbar-win7.png',s+'sync-horizontalbar-win7@2x.png',
	s+'sync-horizontalbar.png',s+'sync-horizontalbar@2x.png',s+'sync-mobileIcon.png',s+'sync-mobileIcon.svg',s+'sync-notification-24.png',
	s+'sync.svg',sx+'horizontalbar-XPVista7.png',sx+'horizontalbar-XPVista7@2x.png',sx+'horizontalbar-win7.png',
	sx+'horizontalbar-win7@2x.png',sx+'horizontalbar.png',sx+'horizontalbar@2x.png',sx+'menuPanel.png',
	sx+'menuPanel@2x.png',sx+'toolbar-XPVista7.png',sx+'toolbar-XPVista7@2x.png',sx+'toolbar-inverted.png',
	sx+'toolbar-inverted@2x.png',sx+'toolbar.png',sx+'toolbar@2x.png',s+'synced-tabs.svg',
	s+'tab-crashed.svg',s+'tab.svg',st+'alltabs-box-bkgnd-icon-inverted.png',st+'alltabs-box-bkgnd-icon-inverted@2x.png',
	st+'alltabs-box-bkgnd-icon.png',st+'alltabs-box-bkgnd-icon@2x.png',st+'alltabs-inverted.png',st+'alltabs.png',
	st+'badge-audio-playing.svg',st+'connecting.png',st+'connecting@2x.png',st+'crashed.svg',
	st+'indicator-tab-attention.svg',st+'loading-20fps.svg',st+'loading-30fps.svg',st+'loading-burst.svg',
	st+'loading.png',st+'loading.svg',st+'loading@2x.png',st+'newtab-XPVista7.png',
	st+'newtab-XPVista7.svg',st+'newtab-XPVista7@2x.png',st+'newtab-inverted-XPVista7.png',st+'newtab-inverted-XPVista7.svg',
	st+'newtab-inverted-XPVista7@2x.png',st+'newtab-inverted-win7.svg',st+'newtab-inverted.png',st+'newtab-inverted.svg',
	st+'newtab-inverted@2x.png',st+'newtab-win7.svg',st+'newtab.png',st+'newtab.svg',
	st+'newtab@2x.png',st+'pendingpaint.png',st+'tab-active-middle.png',st+'tab-active-middle@2x.png',
	st+'tab-arrow-left-XPVista7.png',st+'tab-arrow-left-XPVista7.svg',st+'tab-arrow-left-XPVista7@2x.png',
	st+'tab-arrow-left-inverted.png',st+'tab-arrow-left-inverted.svg',st+'tab-arrow-left-inverted@2x.png',
	st+'tab-arrow-left-win7.svg',st+'tab-arrow-left.png',st+'tab-arrow-left.svg',st+'tab-arrow-left@2x.png',
	st+'tab-arrow-right-inverted.png',st+'tab-arrow-right-inverted@2x.png',st+'tab-arrow-right.png',
	st+'tab-arrow-right@2x.png',st+'tab-audio-blocked.svg',st+'tab-audio-muted.svg',st+'tab-audio-playing.svg',
	st+'tab-audio-small.svg',st+'tab-audio.svg',st+'tab-background-end-preWin10.png',st+'tab-background-end-preWin10@2x.png',
	st+'tab-background-end.png',st+'tab-background-end@2x.png',st+'tab-background-middle-preWin10.png',
	st+'tab-background-middle-preWin10@2x.png',st+'tab-background-middle.png',st+'tab-background-middle@2x.png',
	st+'tab-background-start-preWin10.png',st+'tab-background-start-preWin10@2x.png',st+'tab-background-start.png',
	st+'tab-background-start@2x.png',st+'tab-connecting.png',st+'tab-connecting@2x.png',st+'tab-loading-inverted.png',
	st+'tab-loading-inverted@2x.png',st+'tab-loading.png',st+'tab-loading@2x.png',st+'tab-overflow-border.png',
	st+'tab-overflow-indicator.png',st+'tab-selected-end.svg',st+'tab-selected-start.svg',st+'tab-separator-XP.png',
	st+'tab-separator-luna-blue.png',st+'tab-separator.png',st+'tab-separator@2x.png',st+'tab-stroke-end.png',
	st+'tab-stroke-end@2x.png',st+'tab-stroke-start.png',st+'tab-stroke-start@2x.png',st+'tab.png',
	st+'tabDragIndicator.png',st+'tabDragIndicator@2x.png',s+'tabview/close.png',s+'tabview/edit-light.png',
	s+'tabview/grain.png',s+'tabview/search.png',s+'tabview/stack-expander.png',s+'tabview/tabview-inverted.png',s+'tabview/tabview.png',
	s+'theme-switcher-icon.png',s+'theme-switcher-icon@2x.png',s+'toolbar.svg',s+'toolbarbutton-dropdown-arrow-XPVista7.png',
	s+'toolbarbutton-dropdown-arrow-inverted.png',s+'toolbarbutton-dropdown-arrow-win7.png',s+'toolbarbutton-dropdown-arrow.png',s+'toolbarbutton-dropmarker.png',
	s+'toolbarbutton-dropmarker@2x.png',s+'tracking-protection-16.svg',s+'tracking-protection-disabled-16.svg',s+'tracking-protection-disabled.svg',
	s+'tracking-protection.svg',s+'translating-16.png',s+'translating-16@2x.png',s+'translation-16.png',s+'translation-16@2x.png',
	s+'undo.svg',s+'undoCloseTab.png',s+'undoCloseTab@2x.png',s+'update-badge-failed.svg',s+'update-badge.svg',
	s+'urlbar-arrow.png',s+'urlbar-arrow@2x.png',s+'urlbar-history-dropmarker-XPVista7.png',s+'urlbar-history-dropmarker-XPVista7@2x.png',
	s+'urlbar-history-dropmarker-preWin10.png',s+'urlbar-history-dropmarker-preWin10@2x.png',s+'urlbar-history-dropmarker-win7.png',
	s+'urlbar-history-dropmarker-win7@2x.png',s+'urlbar-history-dropmarker.png',s+'urlbar-history-dropmarker@2x.png',s+'urlbar-popup-blocked.png',
	s+'urlbar-popup-blocked@2x.png',s+'urlbar-star.svg',s+'urlbar-tab.svg',s+'usercontext/banking.svg',s+'usercontext/personal.svg',
	s+'usercontext/shopping.svg',s+'usercontext/work.svg',s+'warning-white.svg',s+'warning.svg',s+'warning16.png',
	s+'warning16@2x.png',s+'web-notifications-icon.svg',s+'web-notifications-tray.svg',s+'webIDE.svg',s+'webRTC-camera-white-16.png',
	s+'webRTC-microphone-white-16.png',s+'webRTC-screen-white-16.png',s+'webRTC-shareDevice-16.png',s+'webRTC-shareDevice-16@2x.png',
	s+'webRTC-shareDevice-64.png',s+'webRTC-shareDevice-64@2x.png',s+'webRTC-shareMicrophone-16.png',s+'webRTC-shareMicrophone-16@2x.png',
	s+'webRTC-shareMicrophone-64.png',s+'webRTC-shareMicrophone-64@2x.png',s+'webRTC-shareScreen-16.png',s+'webRTC-shareScreen-16@2x.png',
	s+'webRTC-shareScreen-64.png',s+'webRTC-shareScreen-64@2x.png',s+'webRTC-sharingDevice-16.png',s+'webRTC-sharingDevice-16@2x.png',
	s+'webRTC-sharingDevice-menubar.png',s+'webRTC-sharingDevice-menubar@2x.png',s+'webRTC-sharingMicrophone-16.png',s+'webRTC-sharingMicrophone-16@2x.png',
	s+'webRTC-sharingMicrophone-menubar.png',s+'webRTC-sharingMicrophone-menubar@2x.png',s+'webRTC-sharingScreen-16.png',s+'webRTC-sharingScreen-16@2x.png',
	s+'webRTC-sharingScreen-menubar.png',s+'webRTC-sharingScreen-menubar@2x.png',s+'welcome-back.svg',s+'wifi.svg',
	s+'window-controls/close-highcontrast.svg',s+'window-controls/close-themes.svg',s+'window-controls/close.svg',s+'window-controls/maximize-highcontrast.svg',
	s+'window-controls/maximize-themes.svg',s+'window-controls/maximize.svg',s+'window-controls/minimize-highcontrast.svg',s+'window-controls/minimize-themes.svg',
	s+'window-controls/minimize.svg',s+'window-controls/restore-highcontrast.svg',s+'window-controls/restore-themes.svg',s+'window-controls/restore.svg',
	s+'window.svg',sy+'Toolbar.png',sy+'Toolbar@2x.png',sy+'loop/menuPanel.png',sy+'loop/menuPanel@2x.png',
	sy+'loop/toolbar.png',sy+'loop/toolbar@2x.png',sy+'menuPanel-customize.png',sy+'menuPanel-customize@2x.png',
	sy+'menuPanel-exit.png',sy+'menuPanel-exit@2x.png',sy+'menuPanel-help.png',sy+'menuPanel-help@2x.png',
	sy+'menuPanel-small.png',sy+'menuPanel-small@2x.png',sy+'menuPanel.png',sy+'menuPanel@2x.png',
	sy+'preferences/checkbox.png',sy+'preferences/checkbox@2x.png',sy+'reload-stop-go.png',sy+'reload-stop-go@2x.png',
	sy+'sync-horizontalbar.png',sy+'sync-horizontalbar@2x.png',sy+'tab-active-middle-inactive.png',
	sy+'tab-active-middle-inactive@2x.png',sy+'tab-selected-end-inactive.svg',sy+'tab-selected-start-inactive.svg',
	sy+'tab-stroke-end-inactive.png',sy+'tab-stroke-end-inactive@2x.png',sy+'tab-stroke-start-inactive.png',
	sy+'tab-stroke-start-inactive@2x.png',sy+'thumburger.png',sy+'thumburger@2x.png',s+'zoom-in.svg',s+'zoom-out.svg'
	];

	let cssUris = [b+'aboutDialog.css',c+'aboutDialog.css',c+'aboutPrivateBrowsing.css',c+'aboutRobots.css',
	c+'aboutTabCrashed.css',c+'aboutaccounts/aboutaccounts.css',c+'aboutaccounts/fonts.css',
	c+'aboutaccounts/main.css',c+'aboutaccounts/normalize.css',c+'abouthealthreport/abouthealth.css',
	ca+'aboutHome.css',c+'aboutneterror/netError.css',cb+'.css',c+'certerror/aboutCertError.css',
	c+'contentSearchUI.css',c+'customizableui/panelUI.css',cd+'codemirror/codemirror.css',cd+'codemirror/dialog.css',
	cd+'codemirror/mozilla.css',cd+'commandline.css',cd+'connect.css',cd+'cubic-bezier.css',ce+'.css',
	cd+'eyedropper/crosshairs.css',cd+'eyedropper/nocursor.css',cd+'filter-widget.css',
	cd+'fontinspector/font-inspector.css',cd+'framework/dev-edition-promo.css',cd+'framework/options-panel.css',
	cd+'inspector/inspector.css',cd+'layoutview/view.css',cd+'markup-view.css',cd+'mdn-docs.css',cd+'netmonitor.css',
	cd+'profiler/cleopatra/css/devtools.css',cd+'profiler/cleopatra/css/tree.css',cd+'profiler/cleopatra/css/ui.css',
	cd+'ruleview.css',cd+'spectrum.css',cd+'splitview.css',cd+'styleeditor.css',cd+'widgets.css',
	c+'downloads/allDownloadsViewOverlay.css',c+'downloads/contentAreaDownloadsView.css',c+'downloads/download.css',
	c+'downloads/downloads.css',c+'extension-mac-panel.css',c+'extension-mac.css',
	c+'extension-win-panel.css',c+'extension.css',c+'feeds/subscribe.css',c+'loop/css/contacts.css',c+'loop/css/panel.css',
	c+'loop/sdk-content/css/ot.css',cl+'css/common.css',cl+'css/contacts.css',cl+'css/conversation.css',
	cl+'css/panel.css',cl+'css/reset.css',c+'newtab/newTab.css',c+'pageinfo/pageInfo.css',
	c+'places/organizer.css',c+'places/places.css',cq+'css/firasans.css',cq+'css/normalize.css',
	cq+'css/saved.css',cq+'css/signup.css',cp+'aboutPermissions.css',cp+'clearSiteData.css',
	cp+'handlers.css',ci+'/search.css',cp+'search.css',cp+'siteDataSettings.css',
	cp+'sitePermissions.css',c+'remote-newtab/newTab.css',c+'safeMode.css',c+'sanitizeDialog.css',
	c+'search/searchbarBindings.css',c+'searchSuggestionUI.css',c+'sync/aboutSyncTabs.css',c+'sync/customize.css',
	c+'tabbrowser.css',c+'tabview.css',c+'usercontext/usercontext.css',s+'aboutCertError.css',s+'aboutLibrary.css',
	s+'aboutNetError.css',s+'aboutPrivateBrowsing.css',s+'aboutProviderDirectory.css',s+'aboutRestartRequired.css',
	s+'aboutSessionRestore.css',s+'aboutSocialError.css',s+'aboutSyncTabs.css',s+'aboutTabCrashed.css',
	s+'aboutWelcomeBack.css',s+'blockedSite.css',s+'browser-lightweightTheme.css',s+'browser.css',s+'compacttheme.css',
	se+'panel.css',sc+'panelUI.css',sc+'panelUIOverlay.css',s+'devedition.css',sd+'animationinspector.css',
	sd+'app-manager/connection-footer.css',sd+'app-manager/device.css',sd+'app-manager/help.css',sd+'app-manager/index.css',
	sd+'app-manager/projects.css',sd+'canvasdebugger.css',sd+'commandline.css',sd+'common.css',sd+'computedview.css',
	sd+'dark-theme.css',sd+'debugger.css',sd+'eyedropper.css',sd+'floating-scrollbars-light.css',
	sd+'floating-scrollbars.css',sd+'font-inspector.css',sd+'inspector.css',sd+'layoutview.css',
	sd+'light-theme.css',sd+'markup-view.css',sd+'memory.css',sd+'netmonitor.css',sd+'performance.css',
	sd+'profiler.css',sd+'projecteditor/projecteditor.css',sd+'promisedebugger.css',sd+'ruleview.css',
	sd+'scratchpad.css',sd+'shadereditor.css',sd+'splitview.css',sd+'storage.css',sd+'styleeditor.css',
	sd+'timeline.css',sd+'webaudioeditor.css',sd+'webconsole.css',sd+'webconsole_networkpanel.css',
	sd+'widgets.css',sf+'allDownloadsView.css',sf+'allDownloadsViewOverlay.css',
	sf+'contentAreaDownloadsView.css',sf+'downloads.css',s+'engineManager.css',
	s+'error-pages.css',s+'feeds/subscribe-ui.css',s+'feeds/subscribe.css',s+'in-content/common.css',
	s+'newtab/newTab.css',s+'pageInfo.css',sq+'editBookmark.css',sq+'editBookmarkOverlay.css',
	sq+'organizer.css',sq+'places.css',sp+'aboutPermissions.css',sp+'applications.css',
	sp+'containers.css',sp+'in-content-new/containers.css',sp+'in-content-new/dialog.css',
	sp+'in-content-new/preferences.css',sp+'in-content-new/search.css',sp+'in-content-new/siteDataSettings.css',
	sp+'in-content/containers.css',sp+'in-content/dialog.css',sp+'in-content/preferences.css',
	sp+'in-content/privacy.css',sp+'in-content/search.css',sp+'in-content/siteDataSettings.css',
	sp+'in-content/syncDisconnect.css',sp+'preferences.css',sp+'search.css',s+'privatebrowsing/aboutPrivateBrowsing.css',
	s+'readinglist/sidebar.css',s+'sanitizeDialog.css',s+'searchReset.css',s+'searchbar.css',s+'setDesktopBackground.css',
	s+'syncCommon.css',s+'syncProgress.css',s+'syncQuota.css',s+'syncSetup.css',s+'syncedtabs/sidebar.css',
	s+'tabview/tabview.css',s+'webRTC-indicator.css',g+'aboutCheckerboard.css',g+'aboutMemory.css',g+'aboutMozilla.css',
	g+'aboutTelemetry.css',g+'aboutUrlClassifier.css',g+'aboutwebrtc/aboutWebrtc.css',g+'accessibility/AccessFu.css',
	g+'alerts/alert.css',g+'autocomplete.css',g+'bindings/datetimebox.css',g+'bindings/videocontrols.css',g+'buildconfig.css',
	g+'commonDialog.css',g+'components.css',g+'console.css',g+'crashes.css',g+'customizeToolbar.css',
	g+'menulist.css',g+'plugins.css',g+'resetProfile.css',g+'simplifyMode.css',
	g+'tabprompts.css',g+'textbox.css',g+'viewSource.css',g+'xml/XMLMonoPrint.css',g+'xml/XMLPrettyPrint.css',
	g+'xul.css'
	];
	//g+'minimal-xul.css' removed : causes crashes in Windows7 FF60+61+ESR, but not TB8
	// let cssUris = [g+'minimal-xul.css'];

	// JS
	let allHash = [],
		jsHash = []
	jsUris.forEach(function(src) {
		let script = document.createElement('script')
		script.src = src
		document.head.appendChild(script)
		script.onload = function() {
			jsHash.push(src)
			allHash.push(src)
		};
		document.head.removeChild(script)
	})
	// IMAGES
	let imgHash = []
	imgUris.forEach(function(imgUri) {
		let img = document.createElement("img");
		img.src = imgUri
		img.style.height = "20px"
		img.style.width = "20px"
		img.onload = function() {
			imgHash.push(imgUri)
			allHash.push(imgUri)
		}
	})
	// CSS
	let cssHash = []
	cssUris.forEach(function(cssUri) {
		let css = document.createElement("link")
		css.href = cssUri
		css.type = "text/css"
		css.rel = "stylesheet"
		document.head.appendChild(css)
		css.onload = function() {
			cssHash.push(cssUri)
			allHash.push(cssUri)
		};
		document.head.removeChild(css)
	})

	function output_chrome() {
		clearInterval(checking)
		// counts
		let foundI = imgHash.length,
			foundJ = jsHash.length,
			foundC = cssHash.length,
			foundA = allHash.length
		// hashes
		let hashI = sha1(imgHash.sort()),
			hashJ = sha1(jsHash.sort()),
			hashC = sha1(cssHash.sort()),
			hashA = sha1(allHash.sort())
		// output
		dom.imgHash = hashI + " ["+ foundI +"/" + imgUris.length +"]"
		dom.jsHash = hashJ  + " ["+ foundJ +"/" +  jsUris.length +"]"
		dom.cssHash = hashC + " ["+ foundC +"/" + cssUris.length +"]"
		let countTested = imgUris.length + jsUris.length + cssUris.length
		dom.allHash = sha1(hashA) + " ["+ foundA +"/"+ countTested +"]"
		// data
		let strAll = allHash.sort().toString()
		let strOut = strAll.replace(/,/gi, '<br>')
		dom.allLoaded.innerHTML = strOut
		// label
		dom.chromeRun = "[ re-run tests ]"
	}
	// wait 5 seconds
	let checking = setInterval(output_chrome, 5000)

};
};
